# -*- coding: utf-8 -*-
"""bilstm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ERjqZ0mLpS4GKEn4CkR3hPxbN0bHKyOS
"""

import pandas as pd
import numpy as np
import re

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from tensorflow.keras.models import Sequential

from tensorflow.keras.layers import (
    Embedding,
    Bidirectional,
    LSTM,
    Dense,
    Dropout
)

from tensorflow.keras.utils import to_categorical

from tensorflow.keras.callbacks import EarlyStopping

data= pd.read_csv("/content/malicious_phish.csv")
data.head()

sample_size = 15000

benign = data[data['type'] == 'benign'].sample(sample_size, random_state=42)

phishing = data[data['type'] == 'phishing'].sample(sample_size, random_state=42)

defacement = data[data['type'] == 'defacement'].sample(sample_size, random_state=42)

malware = data[data['type'] == 'malware'].sample(sample_size, random_state=42)

data = pd.concat([
    benign,
    phishing,
    defacement,
    malware
])

# Shuffle
data = data.sample(frac=1, random_state=42)

print(data['type'].value_counts())

extra_benign = [
    # Popular domains
    "yahoo.com",
    "bing.com",
    "duckduckgo.com",
    "mozilla.org",
    "ubuntu.com",
    "python.org",
    "tensorflow.org",
    "keras.io",
    "pytorch.org",
    "oracle.com",
    "ibm.com",
    "salesforce.com",
    "digitalocean.com",
    "medium.com",
    "quora.com",
    "tumblr.com",
    "twitch.tv",
    "steamcommunity.com",
    "epicgames.com",
    "unity.com",
    "unrealengine.com",
    "canva.com",
    "figma.com",
    "behance.net",
    "dribbble.com",
    "airbnb.com",
    "booking.com",
    "uber.com",
    "ola.com",
    "zomato.com",
    "swiggy.com",
    "imdb.com",
    "weather.com",
    "speedtest.net",
    "archive.org",
    "researchgate.net",
    "geeksforgeeks.org",
    "leetcode.com",
    "codeforces.com",
    "hackerrank.com",
    "google.com",
    "github.com",
    "openai.com",
    "microsoft.com",
    "apple.com",
    "stackoverflow.com",
    "kaggle.com",
    "cloudflare.com",
    "adobe.com",
    "intel.com",
    "nvidia.com",
    "facebook.com",
    "instagram.com",
    "twitter.com",
    "x.com",
    "linkedin.com",
    "reddit.com",
    "discord.com",
    "snapchat.com",
    "pinterest.com",
    "youtube.com",
    "netflix.com",
    "spotify.com",
    "primevideo.com",
    "hotstar.com",
    "amazon.com",
    "ebay.com",
    "walmart.com",
    "flipkart.com",
    "wikipedia.org",
    "coursera.org",
    "udemy.com",
    "edx.org",
    "mit.edu",
    "stanford.edu",
    "paypal.com",
    "visa.com",
    "mastercard.com",
    "stripe.com",
    "bbc.com",
    "cnn.com",
    "nytimes.com",
    "reuters.com",
    "notion.so",
    "dropbox.com",
    "zoom.us",
    "slack.com",
    "gitlab.com",
    "vercel.com",
    "huggingface.co",
    "colab.research.google.com"
]

extra_df = pd.DataFrame({
    'url': extra_benign,
    'type': ['benign'] * len(extra_benign)
})

def clean_url(url):

    url = str(url).lower()

    url = url.replace("https://", "")
    url = url.replace("http://", "")
    url = url.replace("www.", "")

    return url

def extract_url_features(url):

    url = str(url).lower()

    features = {}

    # URL length
    features['url_length'] = len(url)

    # Count digits
    features['digit_count'] = sum(c.isdigit() for c in url)

    # Count special chars
    features['special_count'] = len(re.findall(r'[^a-zA-Z0-9]', url))

    # HTTPS
    features['has_https'] = int("https" in url)

    # IP address detection
    features['has_ip'] = int(
        bool(re.search(r'\d+\.\d+\.\d+\.\d+', url))
    )

    # Suspicious keywords
    suspicious_keywords = [
        'login',
        'verify',
        'secure',
        'account',
        'bank',
        'update',
        'free',
        'bonus',
        'crack',
        'paypal',
        'signin'
    ]

    features['suspicious_keywords'] = int(
        any(word in url for word in suspicious_keywords)
    )

    # Dangerous extensions
    features['has_exe'] = int(".exe" in url)
    features['has_php'] = int(".php" in url)

    # Suspicious TLDs
    suspicious_tlds = ['.xyz', '.tk', '.ru', '.biz']

    features['suspicious_tld'] = int(
        any(tld in url for tld in suspicious_tlds)
    )

    return features

data['clean_url'] = data['url'].apply(clean_url)

data[['url', 'clean_url']].head()

extra_df['clean_url'] = extra_df['url'].apply(clean_url)

data = pd.concat([data, extra_df], ignore_index=True)

data = data.sample(frac=1, random_state=42)

le = LabelEncoder()

data['label'] = le.fit_transform(data['type'])

print(le.classes_)

print(data['label'].value_counts())

"""***TOKENIZATION***"""

tokenizer = Tokenizer(
    char_level=True
)

tokenizer.fit_on_texts(data['clean_url'])

sequences = tokenizer.texts_to_sequences(data['clean_url'])

print(sequences[0][:20])

max_length = 200

X = pad_sequences(
    sequences,
    maxlen=max_length,
    padding='post',
    truncating='post'
)

print(X.shape)

y = to_categorical(data['label'])

print(y.shape)

x_train, x_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=data['label']
)

print(x_train.shape)
print(x_test.shape)

model = Sequential()

# Embedding
model.add(
    Embedding(
        input_dim=len(tokenizer.word_index) + 1,
        output_dim=64,
        input_length=max_length
    )
)

# First BiLSTM
model.add(
    Bidirectional(
        LSTM(64, return_sequences=True)
    )
)

# Second BiLSTM
model.add(
    Bidirectional(
        LSTM(32)
    )
)

# Dropout
model.add(Dropout(0.4))

# Dense
model.add(Dense(32, activation='relu'))

# Output
model.add(Dense(4, activation='softmax'))

# Compile model
model.compile(
    loss='categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=2,
    restore_best_weights=True
)

history = model.fit(
    x_train,
    y_train,
    epochs=15,
    batch_size=128,
    validation_split=0.2,
    callbacks=[early_stop]
)

test_loss, test_accuracy = model.evaluate(x_test, y_test)

print("Test Accuracy:", test_accuracy)

y_pred = model.predict(x_test)

y_pred_classes = np.argmax(y_pred, axis=1)

y_true = np.argmax(y_test, axis=1)

from sklearn.metrics import classification_report

print(classification_report(y_true, y_pred_classes))

def predict_url_dl(url):

    # Clean URL
    url = clean_url(url)
    features = extract_url_features(url)

    # Convert to sequence
    sequence = tokenizer.texts_to_sequences([url])

    # Pad sequence
    padded = pad_sequences(
        sequence,
        maxlen=max_length,
        padding='post',
        truncating='post'
    )

    # Predict
    prediction = model.predict(padded, verbose=0)[0]

    predicted_class = np.argmax(prediction)

    confidence = np.max(prediction)

    classes = le.classes_

    predicted_label = classes[predicted_class]

    # Hybrid feature corrections
    # Strong malware indicators
    if features['has_exe'] == 1:
        predicted_label = "malware"

    # Strong defacement indicators
    if (
    features['has_php'] == 1 or
    "1337" in url or
    "hacked" in url
):
        predicted_label = "defacement"

    # Strong phishing indicators
    if (
    features['suspicious_keywords'] == 1 and
    features['suspicious_tld'] == 1 and
    features['has_exe'] == 0
):
        predicted_label = "phishing"

    # Rule-based dangerous URLs bypass threshold
    if predicted_label in ["malware", "defacement"]:
        final_label = predicted_label

    # Normal confidence handling
    elif confidence < 0.85:
        final_label = "benign"

    else:
        final_label = predicted_label

    print("Confidence:", round(confidence * 100, 2), "%")

    return final_label

benign_urls = [
    "https://linkedin.com",
    "https://netflix.com",
    "https://spotify.com",
    "https://leetcode.com",
    "https://huggingface.co",
    "https://drive.google.com",
    "https://chat.openai.com",
    "https://researchgate.net"
]
phishing_urls = [
    "http://paypal-account-verification.xyz",
    "http://bank-login-secure-update.biz",
    "http://amazon-security-alert.tk",
    "http://free-money-bonus.xyz",
    "http://verify-your-account-now.ru"
]
malware_urls = [
    "http://download-crack-software.ru/keygen.exe",
    "http://virus-loader.biz/malware.exe",
    "http://free-hack-tool.tk/trojan.exe",
    "http://darkweb-tools.ru/backdoor.exe"
]
defacement_urls = [
    "http://hacked-site.org/index.php?id=1337",
    "http://anonymous-hacked-page.tk/index.php",
    "http://defaced-portal.com/hacked.php",
    "http://victim-site.net/index.php?admin=hacked"
]
all_tests = [
    ("BENIGN", benign_urls),
    ("PHISHING", phishing_urls),
    ("MALWARE", malware_urls),
    ("DEFACEMENT", defacement_urls)
]

for category, urls in all_tests:

    print("\n" + "="*60)
    print(category)
    print("="*60)

    for url in urls:

        result = predict_url_dl(url)

        print(f"\nURL: {url}")
        print("Prediction:", result)

# Save BiLSTM model
model.save("bilstm_url_detector.h5")

# Save tokenizer
import pickle

with open("tokenizer.pkl", "wb") as f:
    pickle.dump(tokenizer, f)

# Save label encoder
with open("label_encoder.pkl", "wb") as f:
    pickle.dump(le, f)

from google.colab import files

files.download("bilstm_url_detector.h5")
files.download("tokenizer.pkl")
files.download("label_encoder.pkl")